<a href="https://colab.research.google.com/github/mohitgoyal1409/machine_learning/blob/main/47_popability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns = ['day'],inplace= True)

In [ ]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [ ]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
py = 9/14
pn = 5/14

In [ ]:
print(py,pn)

0.6428571428571429 0.35714285714285715

In [ ]:
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [ ]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [ ]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [ ]:
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [ ]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [ ]:
Pyes = py*Psy*PHotYes*PHighYes*PWeakYes
Pno = pn*Psn*PHotNo*PHighNo*PWeakNo

In [ ]:
print(Pyes)
print(Pno)

0.007054673721340388
0.02742857142857143